### ISSUE TITLE
GUITest fails in headless environment

### ISSUE THREAD

**Issue by psibre** [plison/opendial#13]
Further to #10, [GUITest](https://github.com/plison/opendial/blob/400f94d9133762a4803ec950b6279fe34c88ca77/test/opendial/modules/GUITest.java#L59) also fails in a headless environment, but in the constructor, as the Robot throws the expected, but fatal (to the test), AWTException.

**Comment by psibre** [comment]
See the CI log in my [CI build](https://travis-ci.org/psibre/opendial/builds/78447582) for details.

**Comment by plison** [comment]
OK, should be fixed!

**Comment by psibre** [comment]
@plison confirmed fixed, thanks very much!
