### ISSUE TITLE
Something wrong with XMLDomainReader

### ISSUE THREAD

**Issue by dugu9sword** [plison/opendial#18]
When I import opendial as an external jar in Intellj IDEA with Maven, and take the `example_flightbooking.xml` as an example, an exception occurs as following:

`Exception in thread "main" java.lang.RuntimeException: Resource cannot be found: null\example-flightbooking_nlu.xml`

Then I tracked the exception, and I supposed that there may be something wrong with `XMLDomainReader` in line 199.

```java
String fileName =mainNode.getAttributes().getNamedItem("href").getNodeValue();
String filepath = rootpath + File.separator + fileName; // Line 199
domain.addImportedFiles(new File(filepath));
Document subdoc = XMLUtils.getXMLDocument(filepath);
```

The problem is that, when `rootpath` is null, the `filepath` will start with "null", maybe this line should be replaced by

```java
String filepath = rootpath==null?"":rootpath + File.separator + fileName;
```

**Comment by dugu9sword** [comment]
Since when I use the opendial GUI, I will have to choose the XML file manually, so the file will be represented as an **absolute path**. But if I use opendial as an external repository and import the XML in a hard-code way, the file will be represented as an **relative path**, thus the `rootpath` may be null.

**Comment by plison** [comment]
OK, I changed the code in the master branch, it should now be corrected (let me know if it doesn't).
