### ISSUE TITLE
Problem with voice activity detection

### ISSUE THREAD

**Issue by naiqili** [plison/opendial#19]
Hi, I have a strange problem with the VAD component:

I tried to use the Sphinx ASR, and now it can successfully recognize my speech. However if I use the VAD (by clicking the check box in the speech panel), the system does not process my speech after it is recognized.

For example:
[system]
Welcome to our Norwegian flight-booking system!

[system]
What is your destination?

[user]
MOSS 

Then it stops, without further output. But if I use the textbox as input, everything goes fine.

So is this a bug of the VAD component? Thanks!

**Comment by naiqili** [comment]
I figured out a method to overcome this. It seems that the reason is when adding user input, the conversation floor will be handle to the user. I simply comment the line in the file DialogSystem. But it seems suspicious :)

	public Set<String> addUserInput(SpeechData inputSpeech) {
    		Assignment a = new Assignment(settings.userSpeech, inputSpeech);
    		//a.addPair(settings.floor, "user");
    		return addContent(a);
	}

**Comment by plison** [comment]
mm, I don't really manage to reproduce the problem, but it's probably due to some deadlock condition. Do you also have the same problem when using e.g. Nuance instead of Sphinx? Which other modules are you using (Mary TTS)?

**Comment by naiqili** [comment]
Hi, I am using the Festival TTS component and I think this is the problem.
When I change it to Mary TTS everything is fine. There's probably some
problems with my Festival TTS code. Thanks!

**Comment by plison** [comment]
If you're still having problems, try to create threads to perform the speech synthesis (you can have a look at the latest version of  opendial/plugins/MaryTTS.java, where we are now using Threads to avoid these kinds of deadlock).
