### ISSUE TITLE
Some questions with the toolkit

### ISSUE THREAD

**Issue by dugu9sword** [plison/opendial#21]
Here are some words I can find on the open-dial website:

>
>The rules are essentially high-level templates for probabilistic models. They provide an abstraction layer that allows the system designer to capture the domain in a concise and human-readable form, with a limited number of parameters. In other words, OpenDial can be seen as following a "structured POMDP" approach to dialogue.
>

From my point of view, a POMDP-based SDS should be able to easily transfer from one dialogue state to another, but it seems that open-dial has built a strict structure for the dialogue, what means it is more similar to a hand-crafted rule based SDS, although it can deal with some uncertainty from the automated speech recognition system.

Therefore, is it more an improved rule-based system than a POMDP-like system?

**Comment by dugu9sword** [comment]
Taking the provided `example-flight-booking.xml` as an example, when the system requests me to input a destination, if I type in a date it will ignore it and keep asking for destination.

**Comment by plison** [comment]
Well, the flighbooking example is just a small example (with some naive, handcrafted NLU rules to make things simple), there are of course many other, more advanced ways to specify dialogue domains. OpenDial by itself does not enforce any structure on the dialogue domain, you're free to include any kind of state variables and probabilistic dependencies between them. 

Actually, you can encode any arbitrary POMDP in OpenDial: simple create the initial state variables s_0, one large probability rule for the observation model P(o_t | s_t), one large probability rule for the transition model P(s_{t+1} | s_t, a_m), and one large utility rule for the Q-values Q(s_t,a_m). Each rule having its own set of unknown parameters of course.

This being said, even though the formalism can theoretically encode anything, in practice OpenDial is primarily meant for dialogue domains that do not have large amounts of dialogue data, and must therefore rely on expert knowledge to structure the dialogue domain and reduce the number of parameters to estimate.  See my CSL paper for more information: http://nr.no/~plison/pdfs/cl/probrules-plison-csl2015.pdf

**Comment by dugu9sword** [comment]
Oh that is right, thanks a lot.
