### ISSUE TITLE
Runtime Exception occured: Invalid tag in <domain>: userTurn

### ISSUE THREAD

**Issue by lifefeel** [plison/opendial#24]
Hi.
I downloaded OpenDial toolkit and run on Mac OS X.
When I open example file, the RuntimeException occured like below.

`Cannot use domain: java.lang.RuntimeException: Invalid tag in <domain>: userTurn`

thanks.

**Comment by plison** [comment]
Hi,
Could you let me know which specific example file you are using, as well as the version of OpenDial you have (the one in the master branch of the repository, or another release)?

**Comment by lifefeel** [comment]
I downloaded at OpenDial website. The version is 1.5 released on 05.04.2016. Example is woz-dialogue.xml.

**Comment by plison** [comment]
The file woz-dialogue.xml is not an example of dialogue domain, it contains an example of dialogue history (recorded using a Wizard-of-Oz setup).
