### ISSUE TITLE
Unique relationship types

### ISSUE THREAD

**Issue by antori** [plison/opendial#25]
Hi.
I have a question concerning relational structures. It appears it is not possible to define multiple relationships of the same type depending by the same node. For example, the statement "[John likes>chocolate likes>mint]" produces the structure "[John likes>mint]". While it is easy to get around this by using "[John likes1>chocolate likes2>mint]" and then query it by "John likes{_}>{X}", this is obviously a hack. Is this constraint intended or am I missing something?

Thank you!

**Comment by plison** [comment]
No, it's not really intended, it's just that the implementation of relational structures is at an alpha stage at the moment, and I haven't really found the time to improve upon it so far. But if you would like to adapt or correct the existing code, you're welcome to do so!
