### ISSUE TITLE
Online repository used for Gradle dependencies

### ISSUE THREAD

**Issue by bryandeng** [plison/opendial#9]
Hi Pierre:

Is there any repository (like jCenter) that contains OpenDial?

In our project we use Gradle to handle dependencies and we want such online repository so that it can conveniently bring OpenDial in.

**Comment by plison** [comment]
Hi Boyuan,

Thanks for your interest in OpenDial! I haven't yet put OpenDial in such type of repository, but I'll try to do it today. Will keep you posted.

**Comment by plison** [comment]
OK, I've now added to Bintray a new package that contains two files:
- a ZIP file with the source code (without libraries)
- a runnable JAR file with the OpenDial compiled code (again, without libraries). You'll need to include  the libraries listed in http://github.com/plison/opendial/tree/master/lib in your classpath to make it run. 

Here's the link: https://bintray.com/plison/generic/OpenDial

I don't really know whether that's what you wanted or not. I don't know anything about Gradle (or Maven, for that matter), so if you know more about how it works, feel free to contribute!

**Comment by bryandeng** [comment]
@psibre Can you offer some suggestions?

**Comment by psibre** [comment]
We can solve it using Gradle's builting Ivy engine, see [my pull request](/bryandeng/EllaVator/pull/3).

@plison it would be even better to provide the artifact in a Maven-compatible repository, but that requires locking down some metadata, etc. Easy via Gradle, I'll see if I can contribute a wrapper build script.

@bryandeng we can also do this internally by including OpenDial as a git submodule within EllaVator, and including it as a Gradle subproject. Then we can declare a dependency on `project(':opendial')`.

**Comment by psibre** [comment]
For the record, we've integrated OpenDial in a git submodule, which is then included as a gradle subproject. This allows us to inject custom build logic [from the root buildscript](https://github.com/EllaVator/EllaVator/blob/f3f177d4a61450be6424703fe22b43dcd13e10c4/build.gradle#L28-L71).
For development, this is perfect, and we'll be happy to contribute to OpenDial should you wish to migrate your build to Gradle as well.

**Comment by plison** [comment]
There is now a "gradle" branch that relies on gradle (instead of ant) to build OpenDial.
